# Pull base image

FROM tomcat:8.0.30-jre7

# Set Environment properties

# Copy war file to tomcat webapps folder
#deploy the war file to tomcat server webapp folder

COPY /samplewebapp.war /usr/local/tomcat/webapps/